### PR TITLE
Update 2024_lhc.md

### PR DESCRIPTION
**Pull request by wvangoet**
short little shifty wifty

### CODE REVIEW

**Comment by fsoubelet** [comment]
Thank you @wvangoet 

Is there an entry for some B2 results? Maybe we should link to the one a bit above the B1 VDM_V4 you linked to? It seems to be around midnight, is it valid as a final B2 result?

**Comment by wvangoet** [comment]
Those are indeed the last B2 results, they were done a bit quicker. 
I saw Tobias also put a shift summary on a later log.

**Comment by JoschD** [comment]
@fsoubelet You mean: 3983844  ?

Also: will be merged in #130

**Comment by JoschD** [comment]
Also: will be merged in #130

**Pull request closed without merging**
